spring:
  profiles:
    active:
    - dev
---

server:
  port: 8002

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.0.68:3306/foyoedu?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true             # 数据库名称useUnicode=true
    username: root
    password: foyoedu
    dbcp2:
      min-idle: 10                                           # 数据库连接池的最小维持连接数
      initial-size: 10                                       # 初始化连接数
      max-total: 100                                          # 最大连接数
      max-wait-millis: 30000                                  # 等待连接获取的最大超时时间
    

