spring:
  profiles:
    active:
    - dev
---
server:
  port: 9527

spring:
  application:
    name: foyoedu-zuul

eureka:
  client:
    service-url:
      defaultZone: http://eureka.foyoedu.com:7001/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true

zuul:
  ignored-services: "*"
  routes:
    FOYOEDU-PROVIDER-BASE: /base/**

security:
  basic:
    enabled: true
  user:
    name: foyoedu
    password: foyoedu