spring:
  profiles:
    active:
    - dev
---
server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka.foyoedu.com:7001/eureka/
spring:
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
feign:
  hystrix:
    enabled: true