spring:
  profiles:
    active:
    - dev
---
server:
  port: 8002

spring:
  application:
    name: foyoedu-provider-standart
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true                                           #server.tomcat.uri-encoding=UTF-8

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka.foyoedu.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址