spring:
  profiles:
    active:
    - dev
---
server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka.foyoedu.com:7001/eureka/

feign:
  hystrix:
    enabled: true